### ISSUE TITLE
API endpoint to retrive article body 

### ISSUE THREAD

**Issue by theaaron123** [novaramedia/novaramedia-com#103]
Can you add an endpoint to retrieve article body based on id so I can consume it from my android application 

See: https://github.com/theaaron123/novara-media-reader

**Comment by varffs** [comment]
Hi. @theaaron123 you can get this via the default Wordpress API e.g. https://novaramedia.com/wp-json/wp/v2/posts/25761 You can find the docs for that API here: https://developer.wordpress.org/rest-api/reference/posts/#retrieve-a-post

We are probably going to remove our listed custom endpoints soon as the Wordpress default is more powerful and useful now. You will probably find those endpoints more helpful for your app as you can get more advanced relational data. You will be able to query by category and tag if you want to for example.
