### ISSUE TITLE
Donations page - email field

### ISSUE THREAD

**Issue by fig** [novaramedia/novaramedia-com#88]
This is not a technical issue, but a social issue.

Your donations page offers donors optional fields for a physical address, but no fields for an optional email address. I think this might be a disincentive to potential donors. In fact, I don't just think this is a disincentive, I know it is. I know it is, because I just noped out only 5 mins ago.

Fix:
Offer potential donors an optional field to provide an email address. People (me) are much more likely to donate if they feel a 'thank you' might result.

**Comment by varffs** [comment]
@fig thanks for this suggestion last year. We have now added this option for donors and send an email of thanks to anyone who gives us their email.

**Comment by fig** [comment]
Happy to help.
The only problem now is ... Without a Cummings sized excuse, I'm gonna have to go and donate. Oh well, I'm sure it's worth it. 😁
